import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'To do',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className}  min-h-screen bg-black bg-gradient-to-tr from-purple-500 to-transparent via-transparent bg-no-repeat  text-slate-100 container mx-auto p-4`}
			>
				{children}
			</body>
		</html>
	);
}
